{
  "apiVersion": 1,
  "datasources": [
    {
      "access": "proxy",
      "basicAuth": true,
      "basicAuthPassword": "${AVALOQ_OPENSHIFT_MONITORING_PROMETHEUS_PASSWORD}",
      "basicAuthUser": "${AVALOQ_OPENSHIFT_MONITORING_PROMETHEUS_USERNAME}",
      "editable": false,
      "jsonData": {
        "tlsSkipVerify": true
      },
      "name": "prometheus",
      "orgId": 1,
      "type": "prometheus",
      "url": "https://prometheus-k8s.openshift-monitoring.svc:9091",
      "version": 1
    }
  ]
}
