{
 "title": "Twistlock defender",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "twistlock_active_defenders",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_active_defenders{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}"
    }
   ]
  },
  {
   "title": "twistlock_active_app_firewalls",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_active_app_firewalls{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}"
    }
   ]
  },
  {
   "title": "twistlock_total_defenders",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_total_defenders{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}"
    }
   ]
  },
  {
   "title": "twistlock_protected_containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_protected_containers{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}"
    }
   ]
  },
  {
   "title": "Twistlock Main Events / minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(twistlock_access_events{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}[1m])",
     "legendFormat": "twistlock_access_events"
    },
    {
     "expr": "increase(twistlock_app_firewall_events{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}[1m])",
     "legendFormat": "twistlock_app_firewall_events"
    },
    {
     "expr": "increase(twistlock_defender_events{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}[1m])",
     "legendFormat": "twistlock_defender_events"
    },
    {
     "expr": "increase(twistlock_api_requests{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}[1m])",
     "legendFormat": "twistlock_api_requests"
    }
   ]
  },
  {
   "title": "Twistlock Containers-Hosts Events / minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(twistlock_container_network_firewall_events{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}[1m])",
     "legendFormat": "twistlock_container_network_firewall_events"
    },
    {
     "expr": "increase(twistlock_container_runtime_events{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}[1m])",
     "legendFormat": "twistlock_container_runtime_events"
    },
    {
     "expr": "increase(twistlock_host_network_firewall_events{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}[1m])",
     "legendFormat": "twistlock_host_network_firewall_events"
    },
    {
     "expr": "increase(twistlock_host_runtime_events{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}[1m])",
     "legendFormat": "twistlock_host_runtime_events"
    }
   ]
  },
  {
   "title": "Hosts Compliance Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_hosts_low_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_hosts_low_compliance"
    },
    {
     "expr": "twistlock_hosts_medium_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_hosts_medium_compliance"
    },
    {
     "expr": "twistlock_hosts_high_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_hosts_high_compliance"
    },
    {
     "expr": "twistlock_hosts_critical_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_hosts_critical_compliance"
    }
   ]
  },
  {
   "title": "Hosts Vulnerabilities Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_hosts_low_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_hosts_low_vulnerabilities"
    },
    {
     "expr": "twistlock_hosts_medium_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_hosts_medium_vulnerabilities"
    },
    {
     "expr": "twistlock_hosts_high_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_hosts_high_vulnerabilities"
    },
    {
     "expr": "twistlock_hosts_critical_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_hosts_critical_vulnerabilities"
    }
   ]
  },
  {
   "title": "Containers Compliance Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_containers_low_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_containers_low_compliance"
    },
    {
     "expr": "twistlock_containers_medium_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_containers_medium_compliance"
    },
    {
     "expr": "twistlock_containers_high_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_containers_high_compliance"
    },
    {
     "expr": "twistlock_containers_critical_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_containers_critical_compliance"
    }
   ]
  },
  {
   "title": "Containers Vulnerabilities Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_containers_low_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_containers_low_vulnerabilities"
    },
    {
     "expr": "twistlock_containers_medium_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_containers_medium_vulnerabilities"
    },
    {
     "expr": "twistlock_containers_high_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_containers_high_vulnerabilities"
    },
    {
     "expr": "twistlock_containers_critical_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_containers_critical_vulnerabilities"
    }
   ]
  },
  {
   "title": "Images Compliance Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_images_low_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_images_low_compliance"
    },
    {
     "expr": "twistlock_images_medium_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_images_medium_compliance"
    },
    {
     "expr": "twistlock_images_high_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_images_high_compliance"
    },
    {
     "expr": "twistlock_images_critical_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_images_critical_compliance"
    }
   ]
  },
  {
   "title": "Images Vulnerabilities status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_images_low_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_images_low_vulnerabilities"
    },
    {
     "expr": "twistlock_images_medium_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_images_medium_vulnerabilities"
    },
    {
     "expr": "twistlock_images_high_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_images_high_vulnerabilities"
    },
    {
     "expr": "twistlock_images_critical_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_images_critical_vulnerabilities"
    }
   ]
  },
  {
   "title": "Serverless Compliance Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_serverless_low_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_iserverless_low_compliance"
    },
    {
     "expr": "twistlock_serverless_medium_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_serverless_medium_compliance"
    },
    {
     "expr": "twistlock_serverless_high_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_serverless_high_compliance"
    },
    {
     "expr": "twistlock_serverless_critical_compliance{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_serverless_critical_compliance"
    }
   ]
  },
  {
   "title": "Serverless Vulnerabilities Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_serverless_low_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_serverless_low_vulnerabilities"
    },
    {
     "expr": "twistlock_serverless_medium_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_serverless_medium_vulnerabilities"
    },
    {
     "expr": "twistlock_serverless_high_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_serverless_high_vulnerabilities"
    },
    {
     "expr": "twistlock_serverless_critical_vulnerabilities{instance=\"TWISTLOCK_CONSOLE_HOSTNAME:443\",job=\"twistlock\"}",
     "legendFormat": "twistlock_serverless_critical_vulnerabilities"
    }
   ]
  }
 ]
}