apiVersion: v1
kind: Namespace
metadata:
  name: "{{ idx.value.namespace }}"
---
apiVersion: v1
kind: ConfigMap
data:
  twistlock.cfg: "#  _____          _     _   _            _    \n# |_   _|_      _(_)___| |_| | ___   ___| | __  \n#   | | \\ \\ /\\ / / / __| __| |/ _ \\ / __| |/ /      \n#   | |  \\ V  V /| \\__ \\ |_| | (_) | (__|   <       \n#   |_|   \\_/\\_/ |_|___/\\__|_|\\___/ \\___|_|\\_\\\\     \n\n# This configuration file contains the setup parameters for Twistlock\n# This file is typically stored in the same directory as the installation script (twistlock.sh)\n# To reconfigure settings, update this configuration file and re-run twistlock.sh; state and unchanged settings will persist\n\n\n\n#############################################\n#     Network configuration\n#############################################\n# Each port must be set to a unique value (multiple services cannot share the same port)\n###### Management Console ports #####\n# Sets the ports that the Twistlock management website listens on\n# The system that you use to configure Twistlock must be able to connect to the Twistlock Console on these ports\n# To enable the HTTP listener, set the value of MANAGEMENT_PORT_HTTP (e.g. MANAGEMENT_PORT_HTTP=8081)\n# Accessing Console over plain, unencrypted HTTP isn't recommended, as sensitive information can be exposed\nMANAGEMENT_PORT_HTTP=\nMANAGEMENT_PORT_HTTPS=8083\n\n##### Inter-system communication port ##### \n# Sets the port for communication between the Defender(s) and the Console\nCOMMUNICATION_PORT=8084\n\n##### Certificate common names (optional) #####\n# Determines how to construct the CN in the Console's certificate\n# This value should not be modified unless instructed to by Twistlock Support\nCONSOLE_CN=$(hostname --fqdn 2>/dev/null); if [[ $? == 1 ]]; then CONSOLE_CN=$(hostname); fi\n# Determines how to construct the CN in the Defenders' certificates\n# Each Defender authenticates to the Console with this certificate and each cert must have a unique CN\n# These values should not be modified unless instructed to by Twistlock Support\nDEFENDER_CN=${DEFENDER_CN:-}\n\n#############################################\n#     Twistlock system configuration\n#############################################\n###### Data recovery #####\n# Data recovery automatically exports the full Twistlock configuration to the specified path every 24 hours\n# Daily, weekly, and monthly snapshots are retained\n# The exported configuration can be stored on durable storage or backed up remotely with other tools\n# Sets data recovery state (enabled or disabled)\nDATA_RECOVERY_ENABLED=true\n# Sets the directory to which Twistlock data is exported\nDATA_RECOVERY_VOLUME=/var/lib/twistlock-backup\n\n##### Read only containers #####\n# Sets Twistlock containers' file-systems to read-only\nREAD_ONLY_FS=true\n\n##### Storage paths #####\n# Sets the base directory to store Twistlock local data (db and log files)\nDATA_FOLDER=/var/lib/twistlock\n\n##### Docker socket #####\n# Sets the location of the Docker socket file\nDOCKER_SOCKET=${DOCKER_SOCKET:-/var/run/docker.sock}\n# Sets the type of the Docker listener (TCP or NONE)\nDEFENDER_LISTENER_TYPE=${DEFENDER_LISTENER_TYPE:-NONE}\n\n#### systemd configuration ####\n# Installs Twistlock as systemd service\nSYSTEMD_ENABLED=${SYSTEMD_ENABLED:-false}\n\n#### userid configuration ####\n# Run Twistlock Console processes as root (default, twistlock user account)\n# Typically used to run Console on standard (tcp/443) privileged port for TLS\nRUN_CONSOLE_AS_ROOT=${RUN_CONSOLE_AS_ROOT:-false}\n\n#### SELinux configuration ####\n# If SELinux is enabled in dockerd, enable running Twistlock Console and Defender with a dedicated SELinux label\n# See https://docs.docker.com/engine/reference/run/#security-configuration\nSELINUX_LABEL=disable\n\n#### Console cgroup limits ####\n# Controls console container's resource constraints. Set to \"true\" to run without limits.\n# See https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources\nDISABLE_CONSOLE_CGROUP_LIMITS=false\n\n#############################################\n#      Twistlock repository configuration\n#############################################\n# Sets the version tag of the Twistlock containers\n# Do not modify unless instructed to by Twistlock Support\nDOCKER_TWISTLOCK_TAG=_21_04_421\n"
metadata:
  name: twistlock-console
  namespace: "{{ idx.value.namespace }}"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: console
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: twistlock-console-tls
  name: twistlock-console
  namespace: "{{ idx.value.namespace }}"
spec:
  ports:
  - name: communication-port
    port: 8084
  - name: management-port-https
    port: 8083
  selector:
    name: twistlock-console
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount # Service Account is used for managing security context constraints policies in Openshift (SCC)
metadata:
  name: twistlock-console
  namespace: "{{ idx.value.namespace }}"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: twistlock-console
  namespace: "{{ idx.value.namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: "{{ idx.value.console.storageClassName }}"
---

apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: twistlock-console-{{ idx.value.namespace }}
users:
- system:serviceaccount:{{ idx.value.namespace }}:twistlock-console
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
defaultAddCapabilities: []
requiredDropCapabilities: []
allowedCapabilities: []
allowPrivilegedContainer: false
fsGroup: # Volumes which support ownership management are modified to be owned and writable by the GID specified in fsGroup
  type: RunAsAny
# Value 0 is the same as null from OpenShift docs and is set so validation succeeds
priority: 0
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups: # Supplemental groups are regular Linux groups. When a process runs in Linux, it has a UID, a GID, and one or more supplemental groups.
  type: RunAsAny
volumes:
- '*' # Types of volumes the pod can mount. * is wildcard. https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#authorization-controlling-volumes
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twistlock-console
  namespace: "{{ idx.value.namespace }}"
  labels:
    name: twistlock-console
spec:
  replicas: 1
  selector:
    matchLabels:
      name: twistlock-console
  strategy:
    type: Recreate
  template:
    metadata:
      name: twistlock-console
      namespace: "{{ idx.value.namespace }}"
      labels:
        name: twistlock-console
    spec:
      restartPolicy: Always
      serviceAccountName: twistlock-console
      containers:
      - name: twistlock-console
        image: "{{ idx.value.console.image | default(console_image) }}"
        ports:
        - name: mgmt-https
          containerPort: 8083
        - name: communication
          containerPort: 8084
        env:
        - name: CONFIG_PATH
          value: /data/config/twistlock.cfg
        - name: LOG_PROD
          value: "true"
        - name: DATA_RECOVERY_ENABLED
          value: "true"
        - name: COMMUNICATION_PORT
          value: "8084"
        - name: MANAGEMENT_PORT_HTTPS
          value: "8083"
        - name: MANAGEMENT_PORT_HTTP
          value: ""
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: twistlock-config-volume
          mountPath: "/data/config/"
        - name: console-persistent-volume
          mountPath: "/var/lib/twistlock"
          subPath: "var/lib/twistlock"
        - name: console-persistent-volume
          mountPath: "/var/lib/twistlock-backup"
          subPath: "var/lib/twistlock-backup"
        - name: syslog-socket
          mountPath: "/dev/log"
      volumes:
      - name: console-persistent-volume
        persistentVolumeClaim:
          claimName: "twistlock-console"
      - name: twistlock-config-volume
        configMap:
          name: twistlock-console
      - name: syslog-socket
        hostPath:
          path: "/dev/log"
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: twistlock
  namespace: "{{ idx.value.namespace }}"
  labels:
    name: console
spec:
  host: "{{ idx.value.console.hostname | default('') }}"
  to:
    kind: Service
    name: twistlock-console
    weight: 100
  port:
    targetPort: management-port-https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
