# Copyright 2019 Avaloq Evolution AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Verify playbook compatibility with current ocp version
  import_playbook: helper_playbooks/ocp_compatibility_check.yml
  vars:
    avq_ocp_compatibility: [3]

- name: Verify user in 'acpr_cluster_credentials' variable has required type
  import_playbook: helper_playbooks/cluster_credentials.yml
  vars:
    cluster_credentials_required_type: 'cluster-admin-user'
  when: acpr_cluster_credentials is defined

- name: ACPR | Logging upgrade (pre)
  hosts: localhost
  become: false
  pre_tasks:
    - name: Generate kubeconf path
      set_fact:
        KUBECONFIG: '/tmp/acpr-kube-{{ 10000000|random }}/config'
    - name: Create kubedir
      file:
        path: '{{ KUBECONFIG|dirname }}'
        mode: 0700
        state: directory
  post_tasks:
    - name: Cleanup kubedir
      file:
        path: '{{ KUBECONFIG|dirname }}'
        state: absent
  tasks:
    - block:
      - name: acpr login
        include_role:
          name: avaloq.acpr-auth
          tasks_from: login.yml

      - name: Unschedule fluentd pods
        command: "oc --match-server-version=true -n openshift-logging patch daemonset logging-fluentd -p '{\"spec\": {\"template\": {\"spec\": {\"nodeSelector\": {\"logging-infra-fluentd\": \"false\"}}}}}'"
        environment:
          KUBECONFIG: '{{ KUBECONFIG }}'
        register: output
        changed_when: output.stdout == 'daemonset.extensions/logging-fluentd patched'
        when:
          - not acpr_logging_pv_use_hostpath | bool

      - name: Create backup of network policies
        shell: "oc --match-server-version=true -n openshift-logging get networkpolicy -o yaml > /tmp/networkpolicies_backup"
        environment:
          KUBECONFIG: '{{ KUBECONFIG }}'

      - name: Delete all network policies before upgrade
        command: "oc --match-server-version=true -n openshift-logging delete networkpolicy --all"
        environment:
          KUBECONFIG: '{{ KUBECONFIG }}'

      - name: "Remove openshift-logging namespace"
        command: "oc --match-server-version=true delete project openshift-logging"
        environment:
          KUBECONFIG: '{{ KUBECONFIG }}'
        when:
          - acpr_logging_pv_use_hostpath | bool

      always:
      - name: acpr logout
        include_role:
          name: avaloq.acpr-auth
          tasks_from: logout.yml


- name: ACPR | Import Logging upgrade
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml
  vars:
    ansible_become: true

- name: ACPR | Logging upgrade (post)
  hosts: localhost
  become: false
  pre_tasks:
    - name: Generate kubeconf path
      set_fact:
        KUBECONFIG: '/tmp/acpr-kube-{{ 10000000|random }}/config'
    - name: Create kubedir
      file:
        path: '{{ KUBECONFIG|dirname }}'
        mode: 0700
        state: directory
  post_tasks:
    - name: Cleanup kubedir
      file:
        path: '{{ KUBECONFIG|dirname }}'
        state: absent
  tasks:
    - block:
      - name: acpr login
        include_role:
          name: avaloq.acpr-auth
          tasks_from: login.yml

      - name: Restore backup of network policies
        command: "oc --match-server-version=true -n openshift-logging apply -f /tmp/networkpolicies_backup"
        environment:
          KUBECONFIG: '{{ KUBECONFIG }}'
        changed_when: false

      - name: Remove backup of network policies
        file:
          path: /tmp/networkpolicies_backup
          state: absent

      - name: Schedule fluentd pods
        command: "oc --match-server-version=true -n openshift-logging patch daemonset logging-fluentd -p '{\"spec\": {\"template\": {\"spec\": {\"nodeSelector\": {\"logging-infra-fluentd\": \"true\"}}}}}'"
        environment:
          KUBECONFIG: '{{ KUBECONFIG }}'
        register: output
        changed_when: output.stdout == 'daemonset.extensions/logging-fluentd patched'

      always:
      - name: acpr logout
        include_role:
          name: avaloq.acpr-auth
          tasks_from: logout.yml

- import_playbook: acpr-891-efk-state.yml

- import_playbook: acpr-821-storage-migr.yml

- import_playbook: acpr-240-configure-logging.yml
  vars:
    initialize_es_hostpath: true
