# Copyright 2019 Avaloq Evolution AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Verify playbook compatibility with current ocp version
  import_playbook: helper_playbooks/ocp_compatibility_check.yml
  vars:
    avq_ocp_compatibility: [3]

- name: ACPR | API hardening
  hosts: masters
  any_errors_fatal: true
  become: true
  roles:
    - role: yedit
  tasks:
    - include_role:
        name: avaloq.acpr-hardening
        tasks_from: api.yml

- name: ACPR | Scheduler hardening
  hosts: masters
  any_errors_fatal: true
  become: true
  roles:
    - role: yedit
  tasks:
    - include_role:
        name: avaloq.acpr-hardening
        tasks_from: scheduler.yml

- name: ACPR | Controller hardening
  hosts: masters
  any_errors_fatal: true
  become: true
  roles:
    - role: yedit
  tasks:
    - include_role:
        name: avaloq.acpr-hardening
        tasks_from: controller.yml

- name: ACPR | Config file hardening
  hosts: nodes
  any_errors_fatal: true
  become: true
  roles:
    - role: yedit
  tasks:
    - include_role:
        name: avaloq.acpr-hardening
        tasks_from: config_files.yml

- name: ACPR | Etcd hardening
  hosts: masters
  any_errors_fatal: true
  become: true
  roles:
    - role: yedit
  tasks:
    - include_role:
        name: avaloq.acpr-hardening
        tasks_from: etcd.yml

- name: ACPR | Kubelet hardening
  hosts: nodes
  any_errors_fatal: true
  become: true
  roles:
    - role: yedit
  tasks:
    - include_role:
        name: avaloq.acpr-hardening
        tasks_from: kubelet.yml
