# Copyright 2019 Avaloq Evolution AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: "acpr.images"
description: "All container image references uses full URL"
source: acpr
exec:
  type: YAML
  commands:
    - ${I8R_CLIENT} get pods --all-namespaces -o yaml
condition: |-
  foreach (it : $) {
    foreach (item : it.items) {
      foreach (container : item.spec.containers) {
        image = container.image.trim()
        if (! image ~= "^[-a-zA-Z0-9.]{1,256}.[a-zA-Z0-9()]{1,6}(:[0-9]{1,5})?/[-a-zA-Z0-9]*/[-a-zA-Z0-9]*") {
          return false;
        }
      }
    }
  }
  true;
