# Copyright 2019 Avaloq Evolution AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: "acpr.monitoring_namespace_exists"
description: "OpenShift namespace `acpr-monitoring` exists"
source: acpr
exec:
  type: TEXT
  commands:
    - ${I8R_CLIENT} get namespaces -o name acpr-monitoring
condition: |-
  $.trim() == 'namespace/acpr-monitoring'

---
name: "acpr.monitoring_prometheus_exists"
description: "Exactly one OpenShift pod of `Prometheus` exists"
source: acpr
exec:
  type: TEXT
  commands:
    - ${I8R_CLIENT} get pods -n acpr-monitoring -l app=prometheus -l avaloq.com/app=prometheus-statefulset -o name
condition: |-
  foreach (it : $.split('\n')) {
    pit = it.trim();
    if (pit.length() > 0 && ! pit.matches('^pod/prometheus(-statefulset)?-[0-9]$')) {
      return false;
    }
  }
  true;

---
name: "acpr.monitoring_grafana-dashboard-provisioner_exists"
description: "At least one OpenShift pod of `Avaloq Grafana Dashboard Provisioner` exists"
source: acpr
exec:
  type: TEXT
  commands:
    - ${I8R_CLIENT} get pods -n acpr-monitoring -l app=avaloq-grafana-dashboard-provisioner -l avaloq.com/app=grafana-dashboard-provisioner -o name
condition: |-
  foreach (it : $.split('\n')) {
    pit = it.trim();
    if (pit.length() > 0 && ! pit.matches('^pod/(avaloq-)?grafana-dashboard-provisioner.*$')) {
      return false;
    }
  }
  true;

---
name: "acpr.monitoring_prometheus-rules-provisioner_exists"
description: "At least one OpenShift pod of `Avaloq Prometheus Rule Provisioner` exists"
source: acpr
exec:
  type: TEXT
  commands:
    - ${I8R_CLIENT} get pods -n acpr-monitoring -l app=avaloq-prometheus-rule-provisioner -l avaloq.com/app=prometheus-rule-provisioner -o name
condition: |-
  foreach (it : $.split('\n')) {
    pit = it.trim();
    if (pit.length() > 0 && ! pit.matches('^pod/(avaloq-)?prometheus-rule-provisioner.*$')) {
      return false;
    }
  }
  true;

---
name: "acpr.monitoring_kube-state-metrics_exists"
description: "At least one OpenShift pod of `Kube State Metrics` exists"
source: acpr
exec:
  type: TEXT
  commands:
    - ${I8R_CLIENT} get pods -n acpr-monitoring -l k8s-app=kube-state-metrics -l avaloq.com/app=kube-state-metrics-deployment -o name
condition: |-
  foreach (it : $.split('\n')) {
    pit = it.trim();
    if (pit.length() > 0 && ! pit.matches('^pod/kube-state-metrics(-deployment)?-.*$')) {
      return false;
    }
  }
  true;
