---
- name: ACPR | Process 'acpr_cluster_credentials' variable
  hosts: localhost
  become: false
  tasks:
    - name: Define variable 'cluster_credentials_required_type' if not set
      set_fact:
        cluster_credentials_required_type: 'cluster-admin-user'
      when: not cluster_credentials_required_type is defined

    - name: Ensure all users in variable 'acpr_cluster_credentials' have type set (if type is not set, 'cluster-admin-user' is used)
      set_fact:
        acpr_cluster_credentials: |
          {% set result = [] %}
          {% for item in acpr_cluster_credentials %}
          {% if not item.type is defined %}
          {{ result.append(item | combine({'type': 'cluster-admin-user'})) }}
          {%- else %}
          {{ result.append(item) }}
          {%- endif %}
          {% endfor %}
          {{ result }}

    - name: Check if variable 'acpr_cluster_credentials' contains only users with types 'cluster-admin-user' or 'deployment-user'
      fail:
        msg: "Variable 'acpr_cluster_credentials' contains a user with an unknown type. Allowed types are 'cluster-admin-user' and 'deployment-user'"
      when: acpr_cluster_credentials | rejectattr("type", "search", "cluster-admin-user|deployment-user") | list | length > 0

    - name: Check if variable 'acpr_cluster_credentials' contains only one user with type 'cluster-admin-user'
      fail:
        msg: "Variable 'acpr_cluster_credentials' can contain only one user with type 'cluster-admin-user'"
      when: acpr_cluster_credentials | selectattr('type', 'search', 'cluster-admin-user') | list | length > 1

    - name: Check if variable 'acpr_cluster_credentials' contains only one user with type 'deployment-user'
      fail:
        msg: "Variable 'acpr_cluster_credentials' can contain only one user with type 'deployment-user'"
      when: acpr_cluster_credentials | selectattr('type', 'search', 'deployment-user') | list | length > 1

    - name: If there is only one user and the user is 'cluster-admin-user' it can proceed any time
      set_fact:
        cluster_credentials_required_type: 'cluster-admin-user'
      when: acpr_cluster_credentials | length == 1 and acpr_cluster_credentials | selectattr('type', 'search', 'cluster-admin-user') | list | length == 1

    - name: Check if variable 'acpr_cluster_credentials' contains required type of user
      fail:
        msg: "Variable 'acpr_cluster_credentials' doesn't contain required type ({{ cluster_credentials_required_type }}) of user for this play/task"
      when: acpr_cluster_credentials | selectattr('type', 'search', cluster_credentials_required_type) | list | length == 0

    - name: Select propper user from 'acpr_cluster_credentials' variable
      set_fact:
        acpr_cluster_credentials: "{{ acpr_cluster_credentials | selectattr('type', 'search', cluster_credentials_required_type) | list }}"
