apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Avaloq Container Platform Metrics & Alerting
    openshift.io/display-name: ACPR Monitoring
    openshift.io/node-selector: ''
  name: acpr-monitoring
  labels:
    role: monitoring
    app.kubernetes.io/component: monitoring
spec:
  finalizers:
  - kubernetes
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  labels:
    app.kubernetes.io/component: monitoring
spec:
  podSelector: {}
  policyTypes:
  - Ingress
