{
 "title": "Topic: NFS Server",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nfs_host",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Data troughput",
   "type": "graph",
   "description": "Average data read/ written per second by the _NFS_ daemon",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfsd_disk_bytes_read_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(node_nfsd_disk_bytes_written_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Written"
    }
   ]
  },
  {
   "title": "Reply Cache",
   "type": "graph",
   "description": "Average NFS reply cache operations per second over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfsd_reply_cache_hits_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "irate(node_nfsd_reply_cache_misses_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "irate(node_nfsd_reply_cache_nocache_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Nocache"
    },
    {
     "expr": "irate(node_nfsd_read_ahead_cache_not_found_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Not found"
    }
   ]
  },
  {
   "title": "Stale File Handles",
   "type": "graph",
   "description": "Number of stale file handles within the last 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "idelta(node_nfsd_file_handles_stale_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Stale file handles"
    }
   ]
  },
  {
   "title": "Read Ahead Cache rate",
   "type": "graph",
   "description": "Average number of entries not found in cache  per second over 5 minutes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfsd_read_ahead_cache_not_found_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Not found"
    }
   ]
  },
  {
   "title": "RPC rate",
   "type": "graph",
   "description": "Average number of RPC calls and errors per second over 5 minutes",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    {
     "format": "short",
     "label": "Counter errors (-) / success (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_nfsd_rpc_errors_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Error - {{ error }}"
    },
    {
     "expr": "irate(node_nfsd_server_rpcs_total{instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Number of NFSd kernel threads that are running",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "node_nfsd_server_threads{instance=~\"$nfs_host\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Network Packets rate",
   "type": "graph",
   "description": "Average number of TCP and UDP packets per second over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "pps", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfsd_packets_total{instance=~\"$nfs_host\", proto=\"tcp\"}[5m])",
     "legendFormat": "TCP"
    },
    {
     "expr": "irate(node_nfsd_packets_total{instance=~\"$nfs_host\", proto=\"udp\"}[5m])",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "Requests by method (Proc3)",
   "type": "graph",
   "description": "Average number of NFSv3 requests per second over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfsd_requests_total{proto=\"3\", instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Requests by method (Proc4)",
   "type": "graph",
   "description": "Average number of NFSv4 requests per second over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfsd_requests_total{proto=\"4\", instance=~\"$nfs_host\"}[5m])",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}