{
 "title": "Topic: Host",
 "description": "Prometheus for system metrics. \r\nLoad, CPU, RAM, network, process ... ",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": "label_values(kube_node_labels,node)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "description": "How long the system has been running.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time_seconds{instance=~\"$Node\"} - node_boot_time_seconds{instance=~\"$Node\"}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_time%7Balias%3D%5C%22%24host%5C%22%7D%20-%20node_boot_time%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A25%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Host CPUs",
   "type": "singlestat",
   "description": "Number of CPUs the system has",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "machine_cpu_cores{kubernetes_io_hostname=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "singlestat",
   "description": "Total amount of memory the system has",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "machine_memory_bytes{kubernetes_io_hostname=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "singlestat",
   "description": "Amount of Memory the systems sees as _free_  (i.e. _$total_ - _$buffers_ - _$cached_)",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "description": "Percentage of the amount of memory the system sees as available (i.e. _$free_ + _$buffers_ + _$cached_)",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "((node_memory_MemFree_bytes{instance=~\"$Node\"} + node_memory_Buffers_bytes{instance=~\"$Node\"} + node_memory_Cached_bytes{instance=~\"$Node\"})) / node_memory_MemTotal_bytes{instance=~\"$Node\"} * 100",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22(node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D)%20%2F%20node_memory_MemTotal_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20*%20100%22%2C%22range_input%22%3A%2243201s%22%2C%22end_input%22%3A%222015-9-15%2013%3A54%22%2C%22step_input%22%3A%22%22%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage over the 5 minutes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$Node\"}[5m])) by (mode) * 100 /  count(node_cpu_seconds_total{ instance=~\"$Node\"}) by (mode)",
     "legendFormat": "{{ mode }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22sum(rate(node_cpu_seconds_total%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%20by%20(mode)%20*%20100%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "The systems load average in total",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=~\"$Node\"}",
     "legendFormat": "Load 1m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load5{instance=~\"$Node\"}",
     "legendFormat": "Load 5m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load5%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load15{instance=~\"$Node\"}",
     "legendFormat": "Load 15m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load15%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory distribution used (i.e. _$total_ - _$free_ - _$buffers_ - _$cached_) vs available (i.e. _$free_ + _$buffers_ + _$cached_)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node\"}",
     "legendFormat": "Total",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node\"} - (node_memory_MemAvailable_bytes{instance=~\"$Node\"} or (node_memory_MemFree_bytes{instance=~\"$Node\"} + node_memory_Buffers_bytes{instance=~\"$Node\"} + node_memory_Cached_bytes{instance=~\"$Node\"}))",
     "legendFormat": "Used",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$Node\"} or (node_memory_MemFree_bytes{instance=~\"$Node\"} + node_memory_Buffers_bytes{instance=~\"$Node\"} + node_memory_Cached_bytes{instance=~\"$Node\"})",
     "legendFormat": "Available",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "description": "Memory usage distribution between _$used_, _$free_, _$buffers_, and _$cached_",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node\"} - (node_memory_MemFree_bytes{instance=~\"$Node\"} + node_memory_Buffers_bytes{instance=~\"$Node\"} + node_memory_Cached_bytes{instance=~\"$Node\"})",
     "legendFormat": "Used",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree_bytes{instance=~\"$Node\"}",
     "legendFormat": "Free",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers_bytes{instance=~\"$Node\"}",
     "legendFormat": "Buffers",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached_bytes{instance=~\"$Node\"}",
     "legendFormat": "Cached",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "description": "Average rate of process forks per second over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_forks_total{instance=~\"$Node\"}[5m]) ",
     "legendFormat": "Forks",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "description": "Number of processes in _runnable_ and _blocked_ (i.e. waiting for I/O to complete) state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=~\"$Node\"}",
     "legendFormat": "Processes in runnable state",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=~\"$Node\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "description": "Average number of kernel context switches per second over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(node_context_switches_total{instance=~\"$Node\"}[5m])",
     "legendFormat": "Context Switches",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "description": "Average number of interrupts serviced per second over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(node_intr_total{instance=~\"$Node\"}[5m])",
     "legendFormat": "Interrupts",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "The average network traffic received (RX) and transmitted (TX) per second over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$Node\", device!=\"lo\"}[5m])",
     "legendFormat": "{{ device }} (RX)",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$Node\", device!=\"lo\"}[5m])",
     "legendFormat": "{{ device }} (TX)",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "description": "Data sent and received within one our",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$Node\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$Node\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Filesystem Usage (%)",
   "type": "graph",
   "description": "Disk space used per file system in percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "(node_filesystem_size_bytes{instance=~\"$Node\",device!~\"(tmpfs|selinuxfs|/dev/mapper/docker-253:.*)\",mountpoint!~\"/(run|etc)/.*\"} - node_filesystem_avail_bytes{instance=~\"$Node\",device!~\"(tmpfs|selinuxfs|/dev/mapper/docker-253:.*)\",mountpoint!~\"/(run|etc)/.*\"})/ node_filesystem_size_bytes{instance=~\"$Node\",device!~\"(tmpfs|selinuxfs|/dev/mapper/docker-253:.*)\",mountpoint!~\"/(run|etc)/.*\"}",
     "legendFormat": "{{ mountpoint }}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(node_filesystem_size_bytes{service_name=\"$Node\"} - node_filesystem_avail_bytes{service_name=\"$Node\"})/ node_filesystem_size_bytes{service_name=\"$Node\"}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "description": "Disk usage in Bytes per file system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "node_filesystem_size_bytes{instance=~\"$Node\",device!~\"(tmpfs|selinuxfs|/dev/mapper/docker-253:.*)\",mountpoint!~\"/(run|etc)/.*\"} - node_filesystem_avail_bytes{instance=~\"$Node\",device!~\"(tmpfs|selinuxfs|/dev/mapper/docker-253:.*)\",mountpoint!~\"/(run|etc)/.*\"}",
     "legendFormat": "Used: {{ mountpoint }}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(node_filesystem_size_bytes{service_name=\"$Node\"} - node_filesystem_avail_bytes{service_name=\"$Node\"})/ node_filesystem_size_bytes{service_name=\"$Node\"}",
     "timeField": "@timestamp"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$Node\",device!~\"(tmpfs|selinuxfs|/dev/mapper/docker-253:.*)\",mountpoint!~\"/(run|etc)/.*\"}",
     "legendFormat": "Size: {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "description": "Percentage of average time spent per second for disk I/O operations over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "irate(node_disk_io_time_seconds_total {instance=~'$Node',device!~'^(md\\\\d+$|dm-|sr0)'}[5m]) * 100",
     "legendFormat": "{{ device }}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "irate(node_disk_io_time_seconds_total {instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m]) / 1000",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "description": "Number of disk I/O operations per second (iops) currently in progress",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "node_disk_io_now{instance=~\"$Node\",device!~\"sr0\"}",
     "legendFormat": "{{ device }}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total {instance=~\"$Node\",device!~\"sr0\"}[1m])",
     "legendFormat": "{{ device }} io time"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "graph",
   "description": "Average per second disk throughput (r/w) over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$Node\",device!~\"sr0\"}[5m])",
     "legendFormat": "{{ device }} read",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$Node\",device!~\"sr0\"}[5m])",
     "legendFormat": "{{ device }} write"
    }
   ]
  },
  {
   "title": "Memory Management (Paging)",
   "type": "graph",
   "description": "Per second rate of pages stored to (pgpgout) and read (pgpgin) as well as page faults",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "Bps", "label": "PAGING" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "irate(node_vmstat_pgpgin{instance=~\"$Node\"}[5m]) * 1024",
     "legendFormat": "Page In",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "irate(node_vmstat_pgpgout{instance=~\"$Node\"}[5m]) * 1024",
     "legendFormat": "Page Out",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers_bytes%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached_bytes%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "irate(node_vmstat_pgfault{instance=~\"$Node\"}[5m])",
     "legendFormat": "Page faults"
    },
    {
     "expr": "irate(node_vmstat_pgmajfault{instance=~\"$Node\"}[5m])",
     "legendFormat": "Major page faults"
    }
   ]
  },
  {
   "title": "Network interface card (NIC) stats",
   "type": "graph",
   "description": "Average per second drops and errors (_RX_ and _TX_) per NIC over 5 minutes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none", "label": "NET DROP" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "irate(node_network_receive_drop_total {instance=~\"$Node\"}[5m])",
     "legendFormat": "{{ device }}  drops (RX)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "irate(node_network_transmit_drop_total {instance=~\"$Node\"}[5m])",
     "legendFormat": "{{ device }} drops (TX)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "irate(node_network_receive_errs_total {instance=~\"$Node\"}[5m])",
     "legendFormat": "{{ device }} errors (RX)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "irate(node_network_transmit_errs_total {instance=~\"$Node\"}[5m])",
     "legendFormat": "{{ device }} errors (TX)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TCP connection stats",
   "type": "graph",
   "description": "Number of TCP connections in state _established_",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$Node\"}",
     "legendFormat": "TCP connections (established)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}