{
 "title": "Dashboard: OpenShift Cluster CPU Load",
 "description": "Summary of OpenShift Cluster CPU load",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods CPU usage on [[Node]]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_cpu_usage_seconds_total{instance=\"[[Node]]\", id!=\"/\", container_name!=\"POD\", container_name=~\".+\"}[5m]))",
     "legendFormat": "{{namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod restart count rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[5m]))",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "OpenShift pods CPU usage on [[Node]]",
   "type": "graph",
   "description": "OpenShift internal core components CPU usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"[[Node]]\", pod_name=~\"master-.*|sync-.*|sdn-.*|ovs-.*|logging-fluentd-.*\", container_name!=\"POD\", container_name=~\".+\"}[5m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "API requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum(irate(apiserver_request_count{verb=~\"UPDATE|DELETE|DELETECOLLECTION|PATCH|PUT\"}[5m])) by (resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "[[Node]] load 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=\"[[Node]]\"}",
     "legendFormat": "load5"
    }
   ]
  },
  {
   "title": "Nodes load 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU usage on [[Node]]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container_name!=\"POD\", container_name=~\".+\", instance=\"[[Node]]\"}[5m])) / sum (machine_cpu_cores{instance=\"[[Node]]\"}) * 100",
     "legendFormat": "containersCPU%"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporters\",instance=\"[[Node]]\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "nodeCPU%"
    }
   ]
  }
 ]
}