{
 "title": "Topic: OpenShift Project",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(up{kubernetes_namespace=\"$namespace\"}, app)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Project Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of pods in $namespace",
     "type": "singlestat",
     "description": "It includes all pods that belong to this project constellation, including those that did not pass the readiness check",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=~\"$namespace\", created_by_kind!=\"Job\"} * on(pod) kube_pod_status_ready{condition=\"true\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Total pods that passes readiness check",
     "type": "singlestat",
     "description": "It contains the total number of pods that pass the readiness check. If there are differences between total pods and this number then some pods are not ready.",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count (kube_pod_info{namespace=~\"$namespace\", created_by_kind!=\"Job\"} * on(pod) kube_pod_status_ready{condition=\"true\", namespace=~\"$namespace\"}==1)"
      }
     ]
    },
    {
     "title": "Total pods being scrapped successfully by Prometheus",
     "type": "singlestat",
     "description": "Total count of pods that are being scrapped successfully by prometheus",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(up{kubernetes_namespace=~\"^$namespace\"} == 1)"
      }
     ]
    },
    {
     "title": "Logging error or warning exists?",
     "type": "singlestat",
     "description": "Some pods in the project logging error or warning messages. Please check the logs.",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
     "format": "none",
     "valueName": "range",
     "targets": [
      {
       "expr": "sum(rate(log4j2_events_total{kubernetes_namespace=~\"$namespace\", level!=\"info\"}[5m])) "
      }
     ]
    },
    {
     "title": "Rest error calls exists?",
     "type": "singlestat",
     "description": "Some pods in the project are giving rest error responses. Please check the details.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "format": "ops",
     "valueName": "range",
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{kubernetes_namespace=~\"$namespace\", status!~\"2..\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Total CPU usage vs CPU request and limit in $namespace",
     "type": "graph",
     "description": "Compares the CPU Usage to CPU request and limit. Ideally, in a development environment, your usage should be close to the request.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "millicores" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[5m]) * 1000)",
       "legendFormat": "Total CPU usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"} * 1000) ",
       "legendFormat": "Total CPU request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"} * 1000) ",
       "legendFormat": "Total CPU limit"
      }
     ]
    },
    {
     "title": "Total Project Memory Usage vs Memory Request and Limit",
     "type": "graph",
     "description": "It compares the total memory usage vs total memory request for the project over a period of time",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container_name=\"\"})",
       "legendFormat": "Total Project Memory Usage "
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"})",
       "legendFormat": "Total Project Memory Request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"})",
       "legendFormat": "Total Project Memory Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods being available in prometheus target list for $app",
     "type": "table",
     "description": "If pods are not up for scrapping, then detail measurements will not be available in the dashboard",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "up{kubernetes_namespace=~\"^$namespace\", app=~\"$app\"}"
      }
     ]
    },
    {
     "title": "Response Time for the pods in $app",
     "type": "graph",
     "description": "Please note that this is only available for the pods that are up for scrapping from Prometheus perspective",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_max{kubernetes_namespace=~\"^$namespace\", app=~\"$app\"}[5m]) ",
       "legendFormat": "{{app}} {{uri}}"
      }
     ]
    },
    {
     "title": "Request Rate for the pods in $app",
     "type": "graph",
     "description": "Please note this is available only for the pods that are 'up' for scrapping from Prometheus perspective",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{kubernetes_namespace=~\"^$namespace\", app=~\"$app\"}[5m])",
       "legendFormat": "{{app}} {{uri}}"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{kubernetes_namespace=~\"^$namespace\", app=~\"$app\"}[5m]))",
       "legendFormat": "total number of requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage vs CPU request and limit for POD-  $pod",
     "type": "graph",
     "description": "Compares the CPU Usage to CPU request and limit for pod. Ideally, in a development environment, your usage should be close to the request.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "millicores" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", pod_name=~\"$pod\"}[5m]) * 1000) by (pod_name)",
       "legendFormat": "usage- {{pod_name}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$pod\"}*1000) by (pod)",
       "legendFormat": "request-{{pod}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$pod\"}*1000) by (pod)",
       "legendFormat": "limit-{{pod}}"
      }
     ]
    },
    {
     "title": "Memory usage vs limit and request for POD - $pod",
     "type": "graph",
     "description": "Compares the total memory usage of a pod with memory request and limit",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"})",
       "legendFormat": "usage-$pod"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
       "legendFormat": "request-$pod"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
       "legendFormat": "limit-$pod"
      }
     ]
    },
    {
     "title": "CPU Usage breakdown",
     "type": "graph",
     "description": "A breakdown of total CPU time in user time and system time",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "millicores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", pod_name=~\"$pod\"}[5m]) * 1000) by (pod_name)",
       "legendFormat": "Total - {{pod_name}}"
      },
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{namespace=~\"$namespace\", image!=\"\", pod_name=~\"$pod\"}[5m]) * 1000) by (pod_name)",
       "legendFormat": "User - {{pod_name}}"
      },
      {
       "expr": "sum(rate(container_cpu_system_seconds_total {namespace=~\"$namespace\", image!=\"\", pod_name=~\"$pod\"}[5m]) * 1000) by (pod_name)",
       "legendFormat": "System - {{pod_name}}"
      }
     ]
    },
    {
     "title": "POD - $pod is UP",
     "type": "singlestat",
     "description": "Tells whether the pod is scrappable by Prometheus. If it is not scrapable only minimum information is available about the pod through the Kubernetes environment.",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "JVM Memory breakdown for POD - $pod",
     "type": "graph",
     "description": "relates from the used memory how much is dedicated to JVM heap and non-heap. It is currently accurate for Springboot applications.",
     "gridPos": { "h": 18, "w": 13, "x": 11, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\", kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"}) or sum(jvm_memory_bytes_used{area=\"nonheap\", kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"})",
       "legendFormat": "JVM Non Heap used"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{area=\"heap\", kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"}) or sum(jvm_memory_bytes_used{area=\"heap\", kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"})",
       "legendFormat": "JVM Heap used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"}) or sum(jvm_memory_bytes_committed{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"})",
       "legendFormat": "JVM Total Committed"
      },
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"}) or sum(jvm_buffer_pool_used_bytes{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"})",
       "legendFormat": "JVM Buffer"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"})",
       "legendFormat": "Total memory usage for the Pod"
      }
     ]
    },
    {
     "title": "Time Spent rate in GC for POD - $pod",
     "type": "graph",
     "description": "Total time spent in GC related activities for  this pod. This is a rate.",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=~\"^$namespace\", kubernetes_pod_name=\"$pod\"}[5m])) by (kubernetes_pod_name) or sum(rate(jvm_gc_pause_seconds_sum{kubernetes_namespace=~\"^$namespace\", kubernetes_pod_name=\"$pod\"}[5m])) by (kubernetes_pod_name)",
       "legendFormat": "Time spent in GC"
      }
     ]
    },
    {
     "title": "Garbage Collection Rate for POD - $pod",
     "type": "graph",
     "description": "Gives a glimpse at the garbage collection rate of the pod.",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"}[5m]) or  rate(jvm_gc_pause_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"}[5m])",
       "legendFormat": "({{action}}, {{cause}}) or ({{gc}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Detail Plots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus targets",
     "type": "table",
     "description": "If pods are not up for scrapping, then measurements will not be available in the dashboard",
     "gridPos": { "h": 15, "w": 18, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "up{kubernetes_namespace=~\"^$namespace\"}"
      }
     ]
    },
    {
     "title": "Prometheus scrape duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "scrape_duration_seconds{kubernetes_namespace=~\"^$namespace\"}",
       "legendFormat": "{{app}},{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Prometheus samples scraped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "scrape_samples_scraped{kubernetes_namespace=~\"^$namespace\"}",
       "legendFormat": "{{app}}, {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Log4j Error logging rate (/sec)",
     "type": "graph",
     "description": "One can see the error logging rate of pods. Only for the pods that are scraped by Prometheus",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(log4j2_events_total{kubernetes_namespace=\"$namespace\", level!=\"info\"}[5m]) > 0",
       "legendFormat": "{{avq_app}},{{kubernetes_pod_name}},{{level}}"
      }
     ]
    },
    {
     "title": "Rest calls - Error rate (/sec)",
     "type": "graph",
     "description": "Error rate over a configurable amount of time. These metrics only available for pods that are scraped by Prometheus",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{kubernetes_namespace=~\"$namespace\", status!~\"2..\"}[$__interval])) by (status, exception)",
       "legendFormat": "aggregated - {{exception}}, {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_count{kubernetes_namespace=~\"$namespace\", status!~\"2..\"}[$__interval])",
       "legendFormat": "{{avq_app}} - {{exception}} - {{status}}"
      }
     ]
    },
    {
     "title": "Garbage collection rate for all pods up for scrapping",
     "type": "graph",
     "description": "This panel is to compare the how high are the garbage collection rate for all the pods. This is currently accurate for only pods that are scrapped successfully by Prometheus.",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=~\"^$namespace\"}[5m])) by (kubernetes_pod_name) or sum(rate(jvm_gc_pause_seconds_count{kubernetes_namespace=~\"^$namespace\"}[5m])) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory usage across all pods",
     "type": "graph",
     "description": "This panel compares the memory usage of all the pods in the project",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container_name=\"\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}