{
 "title": "Topic: OpenShift Fluentd",
 "description": "A quick dashboard for displaying Fluentd metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(fluentd_status_buffer_total_bytes{plugin_id=\"elasticsearch-apps\"},kubernetes_node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unreachable fluentd instances",
   "type": "singlestat",
   "description": "Number of OpenShift Nodes where _fluentd_ is not running",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"logging-pods\",kubernetes_pod_name=~\"logging-fluentd-.*\"}==0)"
    }
   ]
  },
  {
   "title": "Emit count rate (5m)",
   "type": "graph",
   "description": "Number of messages emitted over the past 5 minutes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(fluentd_output_status_emit_count{kubernetes_node_name=~\"$node\"}[5m])) by (kubernetes_node_name)",
     "legendFormat": "{{ kubernetes_node_name }}"
    }
   ]
  },
  {
   "title": "Output buffer queue length (Max over 1m)",
   "type": "graph",
   "description": "Maximum length of all _fluentd_ output buffer queues over 1 minute",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(fluentd_output_status_buffer_queue_length{kubernetes_node_name=~\"$node\"}[1m])) by (kubernetes_node_name)",
     "legendFormat": "{{ kubernetes_node_name }}"
    }
   ]
  },
  {
   "title": "Output buffer queued size (Max over 1m)",
   "type": "graph",
   "description": "Maximum size of all _fluentd_ output buffer queues over 1 minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(fluentd_output_status_buffer_total_bytes{kubernetes_node_name=~\"$node\"}[1m])) by (kubernetes_node_name)",
     "legendFormat": "{{ kubernetes_node_name }}"
    }
   ]
  },
  {
   "title": "Output retry wait",
   "type": "graph",
   "description": "Number of fluentd output plugin retries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_retry_wait{kubernetes_node_name=~\"$node\"}) by (kubernetes_node_name)",
     "legendFormat": "{{ kubernetes_node_name }}"
    }
   ]
  },
  {
   "title": "Current number of output errors",
   "type": "graph",
   "description": "Current number of errors of the _fluentd_ output plugin",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_num_errors{kubernetes_node_name=~\"$node\"}) by (kubernetes_node_name)",
     "legendFormat": "{{ kubernetes_node_name }}"
    }
   ]
  }
 ]
}