{
 "title": "Topic: OpenShift Cluster",
 "description": "Summary of OpenShift Cluster health",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Load",
   "type": "singlestat",
   "description": "Overall cluster load (_load 1_) of all cluster nodes \n(incl. _application_ and _infra_ nodes)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": " (sum(max(node_load1 ) by (instance)) / sum (max(machine_cpu_cores) by (instance))/ sum(max(machine_cpu_cores)) ) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "description": "Overall memory consumption of all cluster nodes \n(incl. _application_ and _infra_ nodes)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Cluster Filesystem Usage",
   "type": "singlestat",
   "description": "Overall file system usage of all cluster nodes \n(incl. _application_ and _infra_ nodes)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - 100* (sum (node_filesystem_avail_bytes{device!~'tmpfs'}) / sum(node_filesystem_size_bytes{device!~'tmpfs'}))"
    }
   ]
  },
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "description": "Pods in _running_ state in relation to overall cluster pod capacity (incl. _application_ and _infra_ nodes)",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 / sum(kube_node_status_capacity_pods) * sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Number of Nodes",
   "type": "singlestat",
   "description": "Total number of OpenShift Cluster nodes ( _master_, _infra_ and _application_ nodes)",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "description": "OpenShift cluster nodes that are not reachable",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    },
    {}
   ]
  },
  {
   "title": "Number of Application Nodes",
   "type": "singlestat",
   "description": "Total number of OpenShift _application_ nodes which can be used for Application workload",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_uname_info{node_role_kubernetes_io_compute=\"true\"})"
    }
   ]
  },
  {
   "title": "Number of Master Nodes",
   "type": "singlestat",
   "description": "Total number of OpenShift _master_ nodes. In ACPR compliant cluster installations this should be _3_",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_uname_info{node_role_kubernetes_io_master=\"true\"})"
    }
   ]
  },
  {
   "title": "Number of Infrastructure Nodes",
   "type": "singlestat",
   "description": "Total number of OpenShift _infra_ nodes which can  be used for cluster-wide services such as _OpenShift Router_. In ACPR compliant cluster installations this should be at least _3_",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_uname_info{node_role_kubernetes_io_infra=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes NotReady",
   "type": "singlestat",
   "description": "OpenShift cluster nodes that are reachable but marked as _NotReady_ from OpenShift perspective",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_info) - sum(node_uname_info{beta_kubernetes_io_os=\"linux\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "description": "Number of pods in _running_ state throughout the entire cluster",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "description": "Number of pods in _pending_ state throughout the entire cluster",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "description": "Number of pods in _failed_ state throughout the entire cluster",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "description": "Number of pods in _unknown_ state throughout the entire cluster",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "description": "Number of containers in _running_ state throughout the entire cluster",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running)"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "description": "Number of pods in _waiting_ state throughout the entire cluster",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "description": "Number of pods in _terminated_ state throughout the entire cluster. \n\nThis can be due to successful execution (e.g. _openshift-logging_ curator- pod) or a failure during execution.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated)"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "description": "Number of container restarts during last 30 minutes",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))"
    }
   ]
  }
 ]
}