{
 "title": "Topic: OpenShift Elasticsearch",
 "description": "This dashboard is designed to collect information about the Openshift logging framework which is based on Elasticsearch",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Logging Job", "query": "logging-pods" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(es_cluster_nodes_number{job=\"$job\"}, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(es_cluster_nodes_number{job=~\"$job\", cluster=~\"$cluster\"}, es_node)"
   }
  ]
 },
 "panels": [
  { "title": "Overall status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status - $cluster",
   "type": "singlestat",
   "description": "0 => Green, cluster OK all primary and replicas shards present\n1 => Yellow, Some replicas shards are missing, but all data is available\n2 => Red, Some data is missing\nHere, max is used in the expression because 3 data nodes have the same value",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_status{job=~\"$job\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster related",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of nodes in the cluster - $cluster",
     "type": "singlestat",
     "description": "Contains the total value of the nodes in the cluster.\nMax is used because 3 data nodes have the same value.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(es_cluster_nodes_number{job=~\"$job\", cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total number of data nodes in the cluster - $cluster",
     "type": "singlestat",
     "description": "Contains the total value of data nodes in the cluster.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(es_cluster_datanodes_number{job=~\"$job\", cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Active shard percent for cluster: $cluster",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(es_cluster_shards_active_percent{job=\"$job\", cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total number of shards in cluster ($cluster) according to type",
     "type": "graph",
     "description": "total number of shards in the cluster according to the type",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(es_cluster_shards_number{job=\"$job\", cluster=\"$cluster\"}) by (type)",
       "legendFormat": " {{type}}"
      }
     ]
    },
    {
     "title": "Role of the nodes",
     "type": "table",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "es_node_role_bool{job=\"$job\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Is the cluster timed out?",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(es_cluster_is_timedout_bool{job=~\"$job\", cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of indices",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count(es_index_status{job=\"$job\", cluster=\"$cluster\"}) by (index))"
      }
     ]
    },
    {
     "title": "Total number of documents in different nodes of cluster: $cluster",
     "type": "graph",
     "description": "This is the total number of documents in the node. I think this includes the replica copies as well",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(es_indices_doc_number{job=~\"$job\", cluster=~\"$cluster\"})",
       "legendFormat": "Total documents in all indices (including replicas)"
      },
      {
       "expr": "es_indices_doc_number{job=~\"$job\", cluster=~\"$cluster\"}",
       "legendFormat": "node - {{node}}"
      }
     ]
    },
    {
     "title": "Indexed operation rate for cluster: $cluster",
     "type": "graph",
     "description": "This is the total rate of document index operation that took place. It can be higher than the documents rate in the node.  The value is summed across all nodes",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_indices_indexing_index_count{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Total rate"
      },
      {}
     ]
    },
    {
     "title": "Time spent - cluster: $cluster",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(deriv(es_indices_search_query_time_seconds{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Avg time spent per node while searching queries"
      },
      {
       "expr": "avg(deriv(es_indices_indexing_index_time_seconds{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Avg time spent per node while indexing documents:"
      },
      {
       "expr": "avg(deriv(es_indices_search_fetch_time_seconds{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Avg time spent per node while search fetches"
      }
     ]
    },
    {
     "title": "Number of shards per index in cluster - $cluster",
     "type": "table",
     "description": "the total number of shards including primary and replicas",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sort(max(es_index_shards_number{job=~\"$job\", cluster=~\"$cluster\", type=\"active\"}) by (index))"
      }
     ]
    },
    {
     "title": "Number of replicas per index in cluster - $cluster",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sort(max(es_index_replicas_number{job=~\"$job\", cluster=~\"$cluster\"}) by (index))"
      }
     ]
    },
    {
     "title": "Store size of the indices in bytes in nodes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_indices_store_size_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "{{es_node}}"
      }
     ]
    },
    {
     "title": "Growth rate store size of the indices",
     "type": "graph",
     "description": "It is the same value like the store sizes, but it shows the growth rate of the storage",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "deriv(es_indices_store_size_bytes{job=\"$job\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{es_node}}"
      },
      {
       "expr": "sum(deriv(es_indices_store_size_bytes{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices performance KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of search queries and time spent - cluster: $cluster",
     "type": "graph",
     "description": "The rate of search query and time spent is derived from gauge values of total search query count increase and total time increase. Sum in the expression is kind of not very useful but makes the plot look nicer and gives a summed value for the whole cluster.",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_indices_search_query_count{job=\"$job\", cluster=\"$cluster\",node=~\"$node\"}[5m]))",
       "legendFormat": "search query rate -- {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_search_query_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "time spent on search queries -- {{$node}}"
      }
     ]
    },
    {
     "title": "Rate of search fetches and time spent - cluster: $cluster",
     "type": "graph",
     "description": "Search fetch and search execution are two different things. After search gets executed result need to get fetched for showing the results. Sum in the expression is kind of not very useful but makes the plot look nicer and gives a summed value for the whole cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_indices_search_fetch_count{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "rate of search fetches - {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_search_fetch_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "rate of time spent in search fetches - {{$node}}"
      }
     ]
    },
    {
     "title": "Rate of document indexing and time spent indexing - cluster: $cluster",
     "type": "graph",
     "description": "Values are derived from gauge values. Sum in the expression is kind of not very useful but makes the plot look nicer and gives a summed value for the whole cluster.",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_indices_indexing_index_count{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "document indexing rate of {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_indexing_index_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "time spent in indexing documents of {{$node}}"
      }
     ]
    },
    {
     "title": "Rate of index flushes and time spent - cluster: $cluster",
     "type": "graph",
     "description": "The rate of index flushes and time spent is derived from gauge values of total flush count increase and total time increase. Sum in the expression is kind of not very useful but makes the plot look nicer and gives a summed value for the whole cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_indices_flush_total_count{job=\"$job\", cluster=\"$cluster\",node=~\"$node\"}[5m]))",
       "legendFormat": "flush rate -- {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_flush_total_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "time spent on flushing-- {{$node}}"
      }
     ]
    },
    {
     "title": "Rate of documents deleted and time spent - cluster: $cluster",
     "type": "graph",
     "description": "delete rate and time spent in deletes",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_indices_indexing_delete_count{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "delete rate -- {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_indexing_delete_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "time spent in delete -- {{$node}}"
      }
     ]
    },
    {
     "title": "Rate of index merges and time spent - cluster: $cluster",
     "type": "graph",
     "description": "The rate of index merges and time spent is derived from gauge values of total merge count increase and total time increase. Sum in the expression is kind of not very useful but makes the plot look nicer and gives a summed value for the whole cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_indices_merges_total_number{job=\"$job\", cluster=\"$cluster\",node=~\"$node\"}[5m]))",
       "legendFormat": "merge rate -- {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_merges_total_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "time spent on merging -- {{$node}}"
      }
     ]
    },
    {
     "title": "Other rates and time spent",
     "type": "graph",
     "description": "Please see the documentation of elasticsearch for details",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_indices_get_count{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "rate of get commands: {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_suggest_count{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "rate of suggests: {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_search_scroll_count{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "rate of search scrolls: {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_get_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "time spent while get commands: {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_suggest_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "time spent while making suggests: {{$node}}"
      },
      {
       "expr": "sum(deriv(es_indices_search_scroll_time_seconds{job=\"$job\", cluster=\"$cluster\", node=~\"$node\"}[5m]))",
       "legendFormat": "time spent while  search scrolls: {{$node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes stats: OS and Process information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "OS CPU percent and process CPU percent for cluster: $cluster",
     "type": "graph",
     "description": "More information can be found:\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "es_os_cpu_percent{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "os-cpu-usage percent for whole node {{node}}"
      },
      {
       "expr": "es_process_cpu_percent{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "process-cpu-percent for node {{node}}"
      }
     ]
    },
    {
     "title": "Elastisearch OS load average for the cluster: $cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_os_load_average_one_minute{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "one minute: {{es_node}}"
      },
      {
       "expr": "es_os_load_average_five_minutes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "five minutes:  {{es_node}}"
      },
      {
       "expr": "es_os_load_average_fifteen_minutes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "fifteen minutes:  {{es_node}}"
      }
     ]
    },
    {
     "title": "Total, used and free memory for the whole node: $cluster",
     "type": "graph",
     "description": "More information can be found in: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html",
     "gridPos": { "h": 8, "w": 7, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_os_mem_total_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "total for node: {{node}}"
      },
      {
       "expr": "es_os_mem_free_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "free for node: {{node}}"
      },
      {
       "expr": "es_os_mem_used_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "used for node: {{node}}"
      }
     ]
    },
    {
     "title": "Virtual memory that is guaranteed to be available to cluster: $cluster",
     "type": "graph",
     "description": "Further information can be found: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_process_mem_total_virtual_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "memory used by ES process - node: {{node}}"
      }
     ]
    },
    {
     "title": "File descriptor related cluster: $cluster",
     "type": "graph",
     "description": "detail information can be found here:\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html",
     "gridPos": { "h": 9, "w": 7, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_process_file_descriptors_open_number{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "open file descriptor: {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes stats: FS information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "File system related: $cluster",
     "type": "graph",
     "description": "Detail information can be found: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "es_fs_total_total_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "Total size (in bytes) of all file stores: {{node}}"
      },
      {
       "expr": "es_fs_total_available_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "Actual amount of free disk space the Elasticsearch node can utilise: {{mount}}, {{type}}, {{node}}"
      }
     ]
    },
    {
     "title": "IO operation related: $cluster",
     "type": "graph",
     "description": "Detail information can be found: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_fs_io_total_operations{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "total IO operations - node: {{node}}"
      },
      {
       "expr": "es_fs_io_total_write_operations{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "write IO operations - node: {{node}}"
      },
      {
       "expr": "es_fs_io_total_read_operations{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "read IO operations - node: {{node}}"
      }
     ]
    },
    {
     "title": "IO read write rates in bytes $cluster",
     "type": "graph",
     "description": "Detail information can be found: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(es_fs_io_total_read_bytes{job=\"$job\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{es_node}} - read rate"
      },
      {
       "expr": "deriv(es_fs_io_total_write_bytes{job=\"$job\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{es_node}} - write rate"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM related",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Detail View",
     "type": "graph",
     "gridPos": { "h": 13, "w": 16, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "es_jvm_mem_nonheap_used_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "JVM non heap used: {{node}}"
      },
      {
       "expr": "es_jvm_mem_heap_used_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "JVM Heap used: {{node}}"
      },
      {
       "expr": "es_jvm_mem_heap_committed_bytes{job=\"$job\", cluster=\"$cluster\"} + es_jvm_mem_nonheap_committed_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "JVM Total Committed: {{node}}"
      }
     ]
    },
    {
     "title": "GC collections count rate and total time rate",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(es_jvm_gc_collection_time_seconds{job=\"$job\", cluster=\"$cluster\"}[5m])) by (es_node)",
       "legendFormat": "{{es_node}} - gc collection time"
      },
      {
       "expr": "sum(deriv(es_jvm_gc_collection_count{job=\"$job\", cluster=\"$cluster\"}[5m])) by (es_node)",
       "legendFormat": "gc collections rate: {{es_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpool related",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of rejected thread in cluster:$cluster",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(es_threadpool_threads_count{cluster=~\"$cluster\", job=~\"$job\", type=\"rejected\"})"
      }
     ]
    },
    {
     "title": "Threadpool: total vs active in node ($node) for cluster: $cluster",
     "type": "graph",
     "description": "Definition of active and thread can be found here:\nhttps://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_threadpool_threads_number{job=\"$job\", cluster=\"$cluster\", type!~\"largest\", es_node = \"$node\"}",
       "legendFormat": "{{name}}, {{type}}, {{node}}"
      }
     ]
    },
    {
     "title": "Number of tasks in the queue of threadpool of node ($node) for cluster: $cluster",
     "type": "graph",
     "description": "Shows the tasks that are in the queue",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_threadpool_tasks_number{job=\"$job\", cluster=\"$cluster\", es_node=\"$node\"}",
       "legendFormat": "{{name}}, {{type}}, {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Circuit breaker sizes for cluster: $cluster",
     "type": "graph",
     "description": "Circuit breakers used to prevent operations from causing an OutOfMemoryError.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_circuitbreaker_estimated_bytes{job=~\"$job\", cluster=\"$cluster\", es_node=\"$node\"}",
       "legendFormat": "estimate for {{node}} - {{name}}"
      },
      {
       "expr": "es_circuitbreaker_limit_bytes{job=~\"$job\", cluster=\"$cluster\",  es_node=\"$node\"}",
       "legendFormat": "limit for  {{node}} - {{name}}"
      }
     ]
    },
    {
     "title": "Circuit breakers stats for cluster: $cluster",
     "type": "graph",
     "description": "Details can be found: https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_circuitbreaker_overhead_ratio{job=\"$job\", cluster=\"$cluster\", es_node=\"$node\"}",
       "legendFormat": "overhead ratio {{node}} - {{name}}"
      },
      {
       "expr": "es_circuitbreaker_tripped_count{job=\"$job\", cluster=\"$cluster\", es_node=\"$node\"}",
       "legendFormat": "tripped count {{node}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query cache related",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query cache size in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_indices_querycache_cache_size_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "total query cache size on node: {{node}}"
      },
      {
       "expr": "es_indices_querycache_memory_size_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "used out of total size: {{node}}"
      }
     ]
    },
    {
     "title": "Query cache stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_indices_querycache_miss_number{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "cache miss count: {{node}}"
      },
      {
       "expr": "es_indices_querycache_hit_count{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "cache hit count: {{node}}"
      },
      {
       "expr": "es_indices_querycache_evictions_count{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "cache eviction count: {{node}}"
      },
      {
       "expr": "es_indices_querycache_total_number{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "query cache usages??:{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request cache related",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request cache size in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_indices_requestcache_memory_size_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "request cache size on node: {{node}}"
      }
     ]
    },
    {
     "title": "Request cache stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_indices_requestcache_hit_count{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "hit count: {{node}}"
      },
      {
       "expr": "es_indices_requestcache_miss_count{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "miss count: {{node}}"
      },
      {
       "expr": "es_indices_requestcache_evictions_count{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "evictions count: {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of http open connection - cluster: $cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_http_open_server_number{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "current open connections: {{es_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transport layer related",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Opened transport layer connections cluster: $cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_transport_server_open_number{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "{{es_node}}"
      }
     ]
    },
    {
     "title": "Bytes received and bytes sent rate- cluster: $cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "deriv(es_transport_rx_bytes_count{job=\"$job\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "bytes received: {{es_node}}"
      },
      {
       "expr": "deriv(es_transport_tx_bytes_count{job=\"$job\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "bytes sent: {{es_node}}"
      }
     ]
    },
    {
     "title": "Packets received and packets sent rate - cluster: $cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(es_transport_rx_packets_count{job=\"$job\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "packets received - {{es_node}}"
      },
      {
       "expr": "deriv(es_transport_tx_packets_count{job=\"$job\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "packets sent - {{es_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average time spent while generating metrics for cluster: $cluster",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(es_metrics_generate_time_seconds_sum{job=\"$job\", cluster=\"$cluster\"}[5m])/rate(es_metrics_generate_time_seconds_count{job=\"$job\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}