{
 "title": "Topic: OpenShift Node",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": "label_values(kube_node_labels,node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node CPUs",
   "type": "singlestat",
   "description": "Number of CPUs the system has",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{instance=~\"^$Node\"})"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "singlestat",
   "description": "Total amount of memory the system has",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_memory_bytes{instance=~\"^$Node\"}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "description": "How long the system has been running",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$Node\"} - node_boot_time_seconds{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "singlestat",
   "description": "CPU usage of the node (i.e. not _idle_ )",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_cpu_seconds_total{instance=~\"^$Node\", mode!=\"idle\"}) / sum(node_cpu_seconds_total{instance=~\"^$Node\"}) ) * 100"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "singlestat",
   "description": "Memory usage of the node (i.e. _$used_ + _$buffers_ + _$cached_",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"^$Node\"}) - sum(node_memory_MemFree_bytes{instance=~\"^$Node\"}+node_memory_Buffers_bytes{instance=~\"^$Node\"}+node_memory_Cached_bytes{instance=~\"^$Node\"}) ) / sum(node_memory_MemTotal_bytes{instance=~\"^$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Root FS Usage",
   "type": "singlestat",
   "description": "Disk usage of the nodes' root file system (/)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - 100* (sum (node_filesystem_avail_bytes{instance=~\"^$Node\", mountpoint=\"/etc/hostname\"}) / sum(node_filesystem_size_bytes{instance=~\"^$Node\", mountpoint=\"/etc/hostname\"}))"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "description": "CPU usage of the node (i.e. not _idle_ )",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{instance=~\"^$Node\", mode!=\"idle\"}) by (instance)/ sum(node_cpu_seconds_total{instance=~\"^$Node\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "description": "Memory usage of the node (i.e. _$used_ + _$buffers_ + _$cached_",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"^$Node\"} - node_memory_MemFree_bytes{instance=~\"^$Node\"} - node_memory_Buffers_bytes{instance=~\"^$Node\"} - node_memory_Cached_bytes{instance=~\"^$Node\"}) by (instance) / sum(node_memory_MemTotal_bytes{instance=~\"^$Node\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Root FS Usage",
   "type": "graph",
   "description": "Disk usage of the nodes' root file system (/)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100 * (sum (node_filesystem_avail_bytes{instance=~\"^$Node\", mountpoint=\"/etc/hostname\"})  by (instance) / sum(node_filesystem_size_bytes{instance=~\"^$Node\", mountpoint=\"/etc/hostname\"})  by (instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Load Average",
   "type": "graph",
   "description": "The systems load average in total",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"^$Node\"}",
     "legendFormat": "{{ instance }} (1m)"
    },
    {
     "expr": "node_load5{instance=~\"^$Node\"}",
     "legendFormat": "{{ instance }}  (5m)"
    },
    {
     "expr": "node_load15{instance=~\"^$Node\"}",
     "legendFormat": "{{ instance }} (15m)"
    }
   ]
  },
  {
   "title": "Requested CPU Cores",
   "type": "graph",
   "description": "CPU cores requested by all pods running on the node",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node\",container!~\".*job.*\"}) by (node)",
     "legendFormat": "{{node}} (requested)"
    },
    {
     "expr": "machine_cpu_cores{instance=~\"^$Node\"}",
     "legendFormat": "{{ instance }} (host cpu)"
    }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "graph",
   "description": "Memory requested by all pods running on the node",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node\"}) by (node)  ",
     "legendFormat": "{{node}} (requested)"
    },
    {
     "expr": "machine_memory_bytes{instance=~\"^$Node\"}",
     "legendFormat": "{{ instance }} (host memory)"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "graph",
   "description": "Number of pods in running state in comparison to maximum number of Pods per node",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_pod_count{instance=~\"^$Node\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "kube_node_status_capacity_pods{node=~\"^$Node\"}",
     "legendFormat": "{{ node }} (pod limit)"
    }
   ]
  },
  {
   "title": "Avaloq Container Memory Usage",
   "type": "singlestat",
   "description": "Memory Usage of containers provided by Avaloq. _0_ is shown if no Avaloq provided Application is running on the node",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", instance=~\"^$Node\", container_name=~\"avaloq-.*\"})/count(container_memory_usage_bytes{image!=\"\", instance=~\"^$Node\", container_name=~\"avaloq-.*\"})"
    }
   ]
  },
  {
   "title": "Top memory consumer",
   "type": "graph",
   "description": "Top 10 pods in regards of memory consumption",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10,sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name, name, image,kubernetes_io_hostname)))",
     "legendFormat": "{{ pod_name}} on {{ kubernetes_io_hostname }} ({{ image }})"
    }
   ]
  }
 ]
}