apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: avaloq-sealed-secrets
    app.kubernetes.io/part-of: avaloq-sealed-secrets
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: acpr-sealed-secrets
