# Copyright 2019 Avaloq Evolution AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: RH-5.1 | Maintain the default OpenShift cert-file and key-file configuration
  lineinfile:
    path: /etc/etcd/etcd.conf
    line: '{{ item }}'
    regexp: '{{ item.split("=")[0] }}='
    state: present
  loop:
    - 'ETCD_CERT_FILE=/etc/etcd/server.crt'
    - 'ETCD_KEY_FILE=/etc/etcd/server.key'

- name: RH-5.2 | Maintain the default OpenShift setting for the client-cert-auth argument
  lineinfile:
    path: /etc/etcd/etcd.conf
    line: ETCD_CLIENT_CERT_AUTH=true
    regexp: 'ETCD_CLIENT_CERT_AUTH='
    state: present

- name: RH-5.3 | Maintain the OpenShift default values for etcd_auto-tls
  lineinfile:
    path: /etc/etcd/etcd.conf
    line: '#ETCD_AUTO_TLS=false'
    regexp: 'ETCD_AUTO_TLS='
    state: present

- name: RH-5.4 | Maintain the OpenShift default peer-cert-file and peer-key-file arguments for etcd
  lineinfile:
    path: /etc/etcd/etcd.conf
    line: '{{ item }}'
    regexp: '{{ item.split("=")[0] }}='
    state: present
  loop:
    - 'ETCD_PEER_CERT_FILE=/etc/etcd/peer.crt'
    - 'ETCD_PEER_KEY_FILE=/etc/etcd/peer.key'

- name: RH-5.5 | Maintain the OpenShift default configuration for the peer-client-cert-auth
  lineinfile:
    path: /etc/etcd/etcd.conf
    line: 'ETCD_PEER_CLIENT_CERT_AUTH=true'
    regexp: 'ETCD_PEER_CLIENT_CERT_AUTH='
    state: present

- name: RH-5.6 | Maintain the OpenShift default configuration for the peer-auto-tls argument
  lineinfile:
    path: /etc/etcd/etcd.conf
    line: '#ETCD_PEER_AUTO_TLS=false'
    regexp: 'ETCD_PEER_AUTO_TLS='
    state: present

# Since this was removed from CIS 1.3.0 benchmark we remove it if it was set
- name: RH-5.7 | Optionally change the OpenShift default setting for the wal-dir argument
  lineinfile:
    path: /etc/etcd/etcd.conf
    line: '#\1'
    regexp: '(ETCD_WAL_DIR=.*)'
    backrefs: yes
    state: present

# Since this was removed from CIS 1.3.0 benchmark we remove it if it was set
- name: RH-5.8 | Optionally modify the max-wals argument
  lineinfile:
    path: /etc/etcd/etcd.conf
    line: '#\1'
    regexp: '(ETCD_MAX_WALS=.*)'
    backrefs: yes
    state: present
