apiVersion: avaloq/v1
kind: AvaloqParameters
spec:
  parameters:
  - name: AVALOQ_CONTAINER_IMAGE_REGISTRY
    description: URL of the container image registry. Must end with "/", unless you
      set it to null
    value: registry.service.avaloq.com/
    validation:
      required: false
      type: text
      pattern: ^$|^.+/$
  - name: AVALOQ_CONTAINER_IMAGE_NAMESPACE
    value: avaloq/
    validation:
      required: false
      type: text
      pattern: ^$|^.+/$
    description: |
      The namespace of the container image. Must end with "/", unless you set it to an empty value. Example: `avaloq/`
  - name: OPENSHIFT_NAMESPACE
    validation:
      type: text
      required: false
    value: acpr-sealed-secrets
    description: |
      OpenShift namespace where to deploy `avaloq-sealed-secrets-operator`
  - name: AVALOQ_SEALED_SECRETS_REPLICAS
    value: 1
    validation:
      required: false
      type: number
      range:
        min: 0
    description: |
      The number of application replicas.
  - name: AVALOQ_SEALED_SECRETS_REQUESTS_CPU
    value: 5m
    validation:
      required: false
      type: text
    description: |
      The cpu requests of the application. For more information of possible values, please check out the following page. https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  - name: AVALOQ_SEALED_SECRETS_REQUESTS_MEMORY
    value: 512Mi
    validation:
      required: false
      type: text
    description: |
      The memory requests of the application. For more information of possible values, please check out the following page. https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  - name: AVALOQ_SEALED_SECRETS_LIMITS_CPU
    value: 2
    validation:
      required: false
      type: text
    description: |
      The cpu limit of the application. For more information of possible values, please check out the following page. https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  - name: AVALOQ_SEALED_SECRETS_LIMITS_MEMORY
    value: 512Mi
    validation:
      required: false
      type: text
    description: |
      The memory limit of the application. For more information of possible values, please check out the following page. https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-deployer
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
  name: sealed-secrets-deployer
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-viewer
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  name: sealed-secrets-viewer
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: secrets-unsealer
  name: secrets-unsealer
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets/status
  verbs:
  - update
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-controller
  name: sealed-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-unsealer
subjects:
- kind: ServiceAccount
  name: sealed-secrets-controller
  namespace: ${OPENSHIFT_NAMESPACE}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
spec:
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: sealed-secrets-controller
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    avaloq.com/zone: core-internal
  name: sealed-secrets-controller
  namespace: ${OPENSHIFT_NAMESPACE}
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      avaloq.com/app: avaloq-sealed-secrets-operator
      name: sealed-secrets-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: sealed-secrets-controller
        avaloq.com/app: avaloq-sealed-secrets-operator
        avaloq.com/zone: core-internal
    spec:
      containers:
      - image: ${AVALOQ_CONTAINER_IMAGE_REGISTRY}${AVALOQ_CONTAINER_IMAGE_NAMESPACE}avaloq-sealed-secrets:0.2.0-controller0.13.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: sealed-secrets-controller
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        stdin: false
        tty: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        resources:
          limits:
            cpu: ${AVALOQ_SEALED_SECRETS_LIMITS_CPU}
            memory: ${AVALOQ_SEALED_SECRETS_LIMITS_MEMORY}
          requests:
            cpu: ${AVALOQ_SEALED_SECRETS_REQUESTS_CPU}
            memory: ${AVALOQ_SEALED_SECRETS_REQUESTS_MEMORY}
      serviceAccountName: sealed-secrets-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: avaloq-sealed-secrets-operator
  annotations:
    openshift.io/description: Sealed Secrets Controller
    openshift.io/display-name: Sealed Secrets Controller
  name: ${OPENSHIFT_NAMESPACE}
spec:
  finalizers:
  - kubernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-key-admin
  name: sealed-secrets-key-admin
  namespace: ${OPENSHIFT_NAMESPACE}
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-service-proxier
  name: sealed-secrets-service-proxier
  namespace: ${OPENSHIFT_NAMESPACE}
rules:
- apiGroups:
  - ''
  resourceNames:
  - 'http:sealed-secrets-controller:'
  - sealed-secrets-controller
  resources:
  - services/proxy
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: ${OPENSHIFT_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-key-admin
subjects:
- kind: ServiceAccount
  name: sealed-secrets-controller
  namespace: ${OPENSHIFT_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-service-proxier
  name: sealed-secrets-service-proxier
  namespace: ${OPENSHIFT_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-service-proxier
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: ${OPENSHIFT_NAMESPACE}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-controller
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: operator
    avaloq.com/app: avaloq-sealed-secrets-operator
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: ${OPENSHIFT_NAMESPACE}
