# Copyright 2019 Avaloq Evolution AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: resolve FQDN
  command: 'dig +short {{ ansible_fqdn }}'
  check_mode: no
  register: output_dig_fqdn
  changed_when: false

- name: resolve IP address
  command: 'dig +short -x {{ ansible_default_ipv4.address }}'
  check_mode: no
  register: output_dig_ip
  changed_when: false

- name: fail if DNS entries are missing
  fail:
    msg: Make sure the host has proper DNS entries (A & PTR)
  when:
     (output_dig_fqdn.stdout != ansible_default_ipv4.address) or
     (ansible_fqdn + '.' != output_dig_ip.stdout)
