- name: Backup sealed-secret master key
  block:
    - name: Login to OpenShift
      include_role:
        name: avaloq.acpr-auth
        tasks_from: login

    - block:
      - name: Check if namespace exists
        command: oc get project acpr-sealed-secrets
        environment:
          KUBECONFIG: '{{ KUBECONFIG }}'
        register: get_sealedsecrets_project
        failed_when: false
        changed_when: false

      - block:
        - name: Export master key
          command: oc get secret -n acpr-sealed-secrets -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml
          environment:
            KUBECONFIG: '{{ KUBECONFIG }}'
          register: sealed_secret_masterkey

        - name: Store exported master key
          copy:
            dest: '{{ _backup_dir }}/sealed-secrets-master.key'
            content: '{{ sealed_secret_masterkey.stdout }}'
            mode: 0600
        when: get_sealedsecrets_project.rc == 0
  always:
    - name: Logout from OpenShift
      include_role:
        name: avaloq.acpr-auth
        tasks_from: logout
