# Copyright 2019 Avaloq Evolution AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# vars file for avaloq.os-inventory
# Certificates for domains service.avaloq.com and *.service.avaloq.com
acpr_registry_default_cacert: |
  -----BEGIN CERTIFICATE-----
  MIIGwTCCBamgAwIBAgIIRhYjj1/sjEIwDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNV
  BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow
  GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRz
  LmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1
  cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTgxMDEwMTAxNjEwWhcN
  MjAxMDEwMTAxNjEwWjBCMSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0
  ZWQxHTAbBgNVBAMMFCouc2VydmljZS5hdmFsb3EuY29tMIIBIjANBgkqhkiG9w0B
  AQEFAAOCAQ8AMIIBCgKCAQEAxDGRN05r0wHGxOiAPzjB/xiPuj2QfYKPYHOqX8z3
  sPm7JUU9BI1QWTech8rI/xz4KM2j7XCN8w8o/I4A/YTY2LYsOdDfz4HLJZwM0mKw
  eB/R5zc8MlJSv51odH9IrpR057AtxDfOOsvcm0V7rpqyqpwDaXcxa1G1SjCouvH0
  4Hl3f96Nw96QVa1nwEzY1yWFPE7iBUaMX+FlwpXHypEkGzO+r/4QSSDrRMHJ4XIS
  kBbFzIbISiAWPBn9bt9xum5Zvvoby3wDmdzxIzIFmI9ibFcREvxtjBgiTRGP8qkb
  3bpnJG6K4GOvB8TxXbGJPdvWTn6bkffW09aYpPQ12e8VYwIDAQABo4IDRjCCA0Iw
  DAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDgYD
  VR0PAQH/BAQDAgWgMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuZ29kYWRk
  eS5jb20vZ2RpZzJzMS04NzYuY3JsMF0GA1UdIARWMFQwSAYLYIZIAYb9bQEHFwEw
  OTA3BggrBgEFBQcCARYraHR0cDovL2NlcnRpZmljYXRlcy5nb2RhZGR5LmNvbS9y
  ZXBvc2l0b3J5LzAIBgZngQwBAgEwdgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzAB
  hhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wQAYIKwYBBQUHMAKGNGh0dHA6Ly9j
  ZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS9nZGlnMi5jcnQwHwYD
  VR0jBBgwFoAUQMK9J47MNIMwojPX+2yz8LQsgM4wMwYDVR0RBCwwKoIUKi5zZXJ2
  aWNlLmF2YWxvcS5jb22CEnNlcnZpY2UuYXZhbG9xLmNvbTAdBgNVHQ4EFgQUdIOT
  9FRQ5F8jmoRpxH10y6uPtE0wggF8BgorBgEEAdZ5AgQCBIIBbASCAWgBZgB2AKS5
  CZC0GFgUh7sTosxncAo8NZgE+RvfuON3zQ7IDdwQAAABZl16DqkAAAQDAEcwRQIh
  ALPmGm16ljWRU21BssTruL530e/dyskZ9zj3VUUTI+uPAiBAd0wrbDS+u22b9zdA
  HwCQg1jAo80COVCoVjUkNegDAAB1AO5Lvbd1zmC64UJpH6vhnmajD35fsHLYgwDE
  e4l6qP3LAAABZl16EvUAAAQDAEYwRAIgU5n6FGlFWdw040Keu5I7Ng0htqFUQw2i
  u7Gs6jpbpFgCICoTzPXqAioyNAvgDTGKMVkOVLht98q6BotBJYMQ8boAAHUAXqdz
  +d9WwOe1Nkh90EngMnqRmgyEoRIShBh1loFxRVgAAAFmXXoT6AAABAMARjBEAiAL
  FJqB1AkSN0pUzUMSmGAh0FYlCc7Ici02c8eQWT9egAIgclHxpGYx9LNoO+u1megx
  DbXWSB/azqsYI3KqUGBR7PcwDQYJKoZIhvcNAQELBQADggEBAFHtO+Eu1l5xjJ/P
  7iZ6d/Iethf0s/tMo/Ol4spiGMrNd78Ac6lFYg1ijGPyqfYqe1S55JuRslkyZvsh
  S1HHAZnSI9b1LtXZZFSav0Nj9KsIIvwWOEDRTYCFqdeDJs9tSOy/s9pxYtJej2Ki
  irpOgJGKM6cSd18w0xkBYpKWpuhxQ7WDyk/YL+gmEDLdj8woSlR03IBon4NP7vdL
  8FBs9rppsFjnJZoMwiPBRssX01oTI+nDQ3cJEYymhDS4iThgUBYn85FsLYpuQ+fC
  iVerbhtmWsyxL6vz7Dhimhe0f/mMlaxiGc+xermSaSpbYqcFsEQouXy6Tlp2s1EJ
  Mij4rEA=
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIE0DCCA7igAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
  EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
  EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
  ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTExMDUwMzA3MDAwMFoXDTMxMDUwMzA3
  MDAwMFowgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
  EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UE
  CxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQD
  EypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwggEi
  MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC54MsQ1K92vdSTYuswZLiBCGzD
  BNliF44v/z5lz4/OYuY8UhzaFkVLVat4a2ODYpDOD2lsmcgaFItMzEUz6ojcnqOv
  K/6AYZ15V8TPLvQ/MDxdR/yaFrzDN5ZBUY4RS1T4KL7QjL7wMDge87Am+GZHY23e
  cSZHjzhHU9FGHbTj3ADqRay9vHHZqm8A29vNMDp5T19MR/gd71vCxJ1gO7GyQ5HY
  pDNO6rPWJ0+tJYqlxvTV0KaudAVkV4i1RFXULSo6Pvi4vekyCgKUZMQWOlDxSq7n
  eTOvDCAHf+jfBDnCaQJsY1L6d8EbyHSHyLmTGFBUNUtpTrw700kuH9zB0lL7AgMB
  AAGjggEaMIIBFjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNV
  HQ4EFgQUQMK9J47MNIMwojPX+2yz8LQsgM4wHwYDVR0jBBgwFoAUOpqFBxBnKLbv
  9r0FQW4gwZTaD94wNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8v
  b2NzcC5nb2RhZGR5LmNvbS8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5n
  b2RhZGR5LmNvbS9nZHJvb3QtZzIuY3JsMEYGA1UdIAQ/MD0wOwYEVR0gADAzMDEG
  CCsGAQUFBwIBFiVodHRwczovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkv
  MA0GCSqGSIb3DQEBCwUAA4IBAQAIfmyTEMg4uJapkEv/oV9PBO9sPpyIBslQj6Zz
  91cxG7685C/b+LrTW+C05+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2
  RJ17LJ3lXubvDGGqv+QqG+6EnriDfcFDzkSnE3ANkR/0yBOtg2DZ2HKocyQetawi
  DsoXiWJYRBuriSUBAA/NxBti21G00w9RKpv0vHP8ds42pM3Z2Czqrpv1KrKQ0U11
  GIo/ikGQI31bS/6kA1ibRrLDYGCD+H1QQc7CoZDDu+8CL9IVVO5EFdkKrqeKM+2x
  LXY2JtwE65/3YR8V3Idv7kaWKK2hJn0KCacuBKONvPi8BDAB
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIEfTCCA2WgAwIBAgIDG+cVMA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNVBAYTAlVT
  MSEwHwYDVQQKExhUaGUgR28gRGFkZHkgR3JvdXAsIEluYy4xMTAvBgNVBAsTKEdv
  IERhZGR5IENsYXNzIDIgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMTAx
  MDcwMDAwWhcNMzEwNTMwMDcwMDAwWjCBgzELMAkGA1UEBhMCVVMxEDAOBgNVBAgT
  B0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHku
  Y29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRpZmljYXRlIEF1
  dGhvcml0eSAtIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv3Fi
  CPH6WTT3G8kYo/eASVjpIoMTpsUgQwE7hPHmhUmfJ+r2hBtOoLTbcJjHMgGxBT4H
  Tu70+k8vWTAi56sZVmvigAf88xZ1gDlRe+X5NbZ0TqmNghPktj+pA4P6or6KFWp/
  3gvDthkUBcrqw6gElDtGfDIN8wBmIsiNaW02jBEYt9OyHGC0OPoCjM7T3UYH3go+
  6118yHz7sCtTpJJiaVElBWEaRIGMLKlDliPfrDqBmg4pxRyp6V0etp6eMAo5zvGI
  gPtLXcwy7IViQyU0AlYnAZG0O3AqP26x6JyIAX2f1PnbU21gnb8s51iruF9G/M7E
  GwM8CetJMVxpRrPgRwIDAQABo4IBFzCCARMwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
  HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFDqahQcQZyi27/a9BUFuIMGU2g/eMB8GA1Ud
  IwQYMBaAFNLEsNKR1EwRcbNhyz2h/t2oatTjMDQGCCsGAQUFBwEBBCgwJjAkBggr
  BgEFBQcwAYYYaHR0cDovL29jc3AuZ29kYWRkeS5jb20vMDIGA1UdHwQrMCkwJ6Al
  oCOGIWh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2Ryb290LmNybDBGBgNVHSAEPzA9
  MDsGBFUdIAAwMzAxBggrBgEFBQcCARYlaHR0cHM6Ly9jZXJ0cy5nb2RhZGR5LmNv
  bS9yZXBvc2l0b3J5LzANBgkqhkiG9w0BAQsFAAOCAQEAWQtTvZKGEacke+1bMc8d
  H2xwxbhuvk679r6XUOEwf7ooXGKUwuN+M/f7QnaF25UcjCJYdQkMiGVnOQoWCcWg
  OJekxSOTP7QYpgEGRJHjp2kntFolfzq3Ms3dhP8qOCkzpN1nsoX+oYggHFCJyNwq
  9kIDN0zmiN/VryTyscPfzLXs4Jlet0lUIDyUGAzHHFIYSaRt4bNYC8nY7NmuHDKO
  KHAN4v6mF56ED71XcLNa6R+ghlO773z/aQvgSMO3kwvIClTErF0UZzdsyqUvMQg3
  qm5vjLyb4lddJIGvl5echK1srDdMZvNhkREg5L4wn3qkKQmw4TRfZHcYQFHfjDCm
  rw==
  -----END CERTIFICATE-----

num_master_hosts: 0
num_worker_hosts: 0
num_infra_hosts: 0
all_in_one_config: false
# Support OCP4 cust_os_release variables with and withouth leading 'v'.
# Valid values are v3.11.272, v4.6.3, 4.6.3 but not 3.11.272
avq_os_release: "{{ (cust_os_version.split('.')[0] + '.' +  cust_os_version.split('.')[1]) | regex_replace('v?(4\\.[0-9]+)', '\\1') }}"
avq_os_supported_versions:
  - v3.11.420
  - v3.11.439
  - v3.11.465
  - 4.6.19
  - 4.6.26
  - 4.6.29
  - 4.6.38
  - 4.7.18
avq_supported_auth_providers:
  - HTPasswdPasswordIdentityProvider
  - LDAPPasswordIdentityProvider
  - OpenIDIdentityProvider

avq_etcd_versions:
  default: 3.2.28
