apiVersion: avaloq/v1
kind: AvaloqFiles
spec:
  parameters:
  - name: config.yaml
    required: false
    type: text
    value: |
      # openshift-monitoring operator configuration file
  - name: alertmanager.yaml
    required: false
    type: text
    value: |
      "global":
        "resolve_timeout": "5m"
      "receivers":
      - "name": "null"
      "route":
        "group_by":
        - "job"
        "group_interval": "5m"
        "group_wait": "30s"
        "receiver": "null"
        "repeat_interval": "12h"
        "routes":
        - "match":
            "alertname": "Watchdog"
          "receiver": "null"
  - name: prometheus-k8s-htpasswd.yaml
    required: true
    type: text
  - name: thanos-querier-oauth-htpasswd.yaml
    required: true
    type: text
  - name: datasources.yaml
    required: false
    type: text
    value: |
      {
          "apiVersion": 1,
          "datasources": [
              {
                  "access": "proxy",
                  "basicAuth": true,
                  "basicAuthPassword": "",
                  "basicAuthUser": "internal",
                  "editable": false,
                  "jsonData": {
                      "tlsSkipVerify": true
                  },
                  "name": "prometheus",
                  "orgId": 1,
                  "type": "prometheus",
                  "url": "https://prometheus-k8s.openshift-monitoring.svc:9091",
                  "version": 1
              }
          ]
      }
  - name: prometheus.yaml
    required: false
    type: text
---
apiVersion: avaloq/v1
kind: AvaloqParameters
spec:
  parameters:
  - name: AVALOQ_OPENSHIFT_MONITORING_PROMETHEUS_USERNAME
    validation:
      type: text
      required: true
    description: Username of internal user
    value: internal
  - name: AVALOQ_OPENSHIFT_MONITORING_PROMETHEUS_PASSWORD
    validation:
      type: text
      required: true
    description: Password of internal user
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
data:
  config.yaml: ${config.yaml}
---
apiVersion: v1
stringData:
  alertmanager.yaml: ${alertmanager.yaml}
kind: Secret
metadata:
  name: alertmanager-main
type: Opaque
---
apiVersion: v1
stringData:
  datasources.yaml: ${datasources.yaml}
  prometheus.yaml: ${prometheus.yaml}
kind: Secret
metadata:
  name: grafana-datasources
type: Opaque
---
apiVersion: v1
stringData:
  auth: ${prometheus-k8s-htpasswd.yaml}
kind: Secret
metadata:
  name: prometheus-k8s-htpasswd
type: Opaque
---
apiVersion: v1
stringData:
  auth: ${thanos-querier-oauth-htpasswd.yaml}
kind: Secret
metadata:
  name: thanos-querier-oauth-htpasswd
type: Opaque
